### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by JaneX8** [rob121/broadlinkgo#5]
I placed broadlinkgo in a docker container along with some other code wrapped around it. Altough broadlinkgo is cross-platform already and Docker won't add any value for that matter. It is great to manage Broadlinkgo in an existing infrastructure along other Docker containers (also mostly API's), with tools such as Portainer.

I could share some thoughts on it if you'd like. It would be fairly simple to arrange this. It basically only requires one configuration file and some documentation in the case of this project.

**Comment by brianpierson2020** [comment]
Done: https://github.com/brianpierson2020/broadlinkgo-docker

**Comment by JaneX8** [comment]
Great, thanks! :)
