### ISSUE TITLE
The license is missing

### ISSUE THREAD

**Issue by felipediel** [rob121/broadlinkgo#6]
Hey @rob121 what's up.
Would you mind adding a license to this code? I suggest you to use MIT license.
This would encourage me to contribute to it.

**Comment by felipediel** [comment]
I will add support for the RM Mini 3 0x5f36 and the RM4 series. I already have a beta version for users to test. But I will only do this if you guarantee that my lines of code will be free forever.

**Comment by brianpierson2020** [comment]
Yes, I would like to see the MIT license :)

**Comment by rob121** [comment]
License Added!
