### ISSUE TITLE
RM4 Mini

### ISSUE THREAD

**Issue by timothystewart6** [rob121/broadlinkgo#9]
Hi!  Thank you for this!  It seems to work however I haven't been able to successfully train an RM4 Mini.  I added a known device like so:

```
knownDevice{deviceType: 0x648d, name: "Broadlink RM Mini 4", supported: true, ir: true, rf: false, power: false},
```

However learning always times out.  I looked at the PR for the RM3, found the code for the RM4, and I am able to discover it however learning never work.  Any pointers?

**Comment by timothystewart6** [comment]
Also, happy to open a PR for this but want to make sure it works before I do!  The discovery works great, but I can't put the device in learning mode.

**Comment by GunoH** [comment]
@timothystewart6 you might try using the changes in https://github.com/rob121/broadlinkgo/pull/10; that's for RM4 Pro plus, but chances are that it's not hard to get RM4 Mini working as well with those changes.

**Comment by rob121** [comment]
Working on getting rm4 added with @GunoH and others
